### ISSUE TITLE
Custom Transformations

### ISSUE THREAD

**Issue by denrase** [hyperoslo/Sync#124]
Hey,

do you plan to support custom transformations? Say I have a color encoded in a string using the #ARGB format (e.g. #FF00FF00 for green) and i want to persist it as a UIColor in a transformable property in my managed object. Is something like this already supported?

br
denis

**Comment by 3lvis** [comment]
Hey Denis!

We don't have anything for transformables in the foreseeable future. Any examples on use cases for this (meaning, why would you want to store as UIColor instead of just storing the strings?

**Comment by damienromito** [comment]
It would be very usefull if we can use Transformable objects with Sync. Of course, we can use Dictionary or Array with Binary Data, but it's a too complexe if we want get objects with real properties from those Dictionary:

`print("value => \(myNSManagedObject.myTransformableObject.myProperty)") `

...rather than :

```
let myProperty = myNSManagedObject.myTransformableObject["myProperty"] 
print("value => \(myProperty)") 
```

**Comment by 3lvis** [comment]
@damienromito Why not just create a new Core Data table for the new object?

**Comment by damienromito** [comment]
Cause it would be a one-to-one relationship. To understand, my f****ing user object look like this:
````
{user : 
      { name : "myname",
            services : {
                  spotify : {
                         userid : "myuserid",
                         token : "mytocken",
                  },
                  deezer : {
                         userid : "myuserid";
                         secretKey : "mykey",
                         token : "mytoken"
                  }
           }
      }
}
```

**Comment by 3lvis** [comment]
There are 3 observations here.

1.- All entities need a primary key. User entity and User JSON need a primary key. You can either add a `remoteID` attribute to your User table and a `id` to your User JSON, or you could tell Sync to use the `name` as the primary key.

More info here: https://github.com/hyperoslo/Sync#primary-key

2.- If your JSON says "access_token" Sync will map it to `accessToken` in Core Data. But if your JSON says "accessToken" it doesn't know how to transform it to `accessToken` because it only does automatic transformations for `snake_case`. So if you wan to use `accessToken` from your `JSON` you need to tell Sync this. You do it by adding `hyper.remoteKey` (key) and `accesstToken` as value in the user Info.

More info on Attribute Mapping here: https://github.com/hyperoslo/Sync#attribute-mapping

3.- You need an inverse relationship for UserSpotify and User. Meaning that in UserSpotify you need a `user` relationship that point back to the `spotify` relationship on User.

**Comment by damienromito** [comment]
1 - as you explained to me here: http://stackoverflow.com/questions/33397102/assertion-failure-in-sync-changesinentitynamedpredicateparentincontextdat/33407185#33407185 I added the key hyper.isPrimaryKey = YES on the name attribute (thank you again)
 2 -it works without
3 - it works without
4 - the probleme : My UserSpotify was an NSObject and not an NSManagedObject #fail  

 thank you for your help and your work!

this question on stackoverflow : http://stackoverflow.com/questions/33440899/map-a-multi-level-json-object-to-nsmanagedobject-with-hyperolso-sync/

**Comment by 3lvis** [comment]
@damienromito let me know if you have any more issues, or if there's something that I should include in the README, :heart:
