### ISSUE TITLE
Analizer tool reports weird issue

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Sync#129]
<img width="990" alt="screen shot 2015-10-08 at 16 19 12" src="https://cloud.githubusercontent.com/assets/1088217/10369013/5b397d16-6dd8-11e5-86b5-1aa8ab9c9d9a.png">

**Comment by richardoti** [comment]
I guess it is related to Apple's API style.
For example, if you take a look at CoreData code:
```Objective-C
NSError *error;
NSArray *fetchedObjects = [context executeFetchRequest:fetchRequest error:&error];
if (fetchedObjects == nil) {
    // Handle the error.
}
```

We're checking whether method returned something or not. I don't remember any `void` methods in Apple's API that take `NSError *` as an argument.

Source of the code:
https://developer.apple.com/library/ios/documentation/DataManagement/Conceptual/CoreDataSnippets/Articles/fetching.html

**Comment by 3lvis** [comment]
@richardoti That makes sense :)

**Comment by 0ff** [comment]
In fact I think the reason is Swift. If you follow these guidelines (https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html#//apple_ref/doc/uid/TP40014216-CH7-ID10 - namely return a BOOL to indicate success), the API can be ported to Swift 2.0 automatically.

**Comment by 3lvis** [comment]
This seems to be gone now that we have a Swift codebase. Closing.
