### ISSUE TITLE
Help wanted: Using "Sync.changes.." does nothing?

### ISSUE THREAD

**Issue by galinyonchev** [hyperoslo/Sync#132]
I need some help, guys. I am trying to understand how Sync works.
I have a core data model and a JSON file, which is almost the same like the data model. I have a patient with some basic info. One of the attributes is "country". In the core data model it is set to "USA" and in the JSON it is "England". When I use Sync, isn't it expected that my dataStack will change? Here is my code:

        let filePath = NSBundle.mainBundle().pathForResource("test", ofType: "json")
        let data: NSData = NSData(contentsOfFile: filePath!)!
        do {
            let JSON = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions.MutableContainers)
            let arr = Array(arrayLiteral: JSON)
            Sync.changes(arr, inEntityNamed: "Patient", dataStack: ds, completion: { (error) -> Void in
                if let patient: Patient = self.fetchEntity(self.ds.mainContext) {
                    print(patient.country)
                }
            })
        } catch {
            print(error)
        }

Everytime it prints "USA", but not "England". Why so, any ideas?

**Comment by 3lvis** [comment]
@galinyonchev could you share your `test.json` file and an screenshot of your Core Data model?

**Comment by galinyonchev** [comment]
JSON: http://pastebin.com/fwrucLzx
Core Data model:
![screen shot 2015-10-14 at 11 44 02](https://cloud.githubusercontent.com/assets/13518877/10478834/f381ddd6-7268-11e5-9f94-5d4cc3da5516.png)

self.fetchEntity function:
    // fetch entity in chosen context
    func fetchEntity(context: NSManagedObjectContext) -> Patient? {
        let fetchRequest = NSFetchRequest(entityName: "Patient")
        fetchRequest.returnsObjectsAsFaults = false
        let objects = (try! context.executeFetchRequest(fetchRequest)) as! [Patient]
        if let obj: Patient = objects.first {
            return obj
        }
        return nil
    }

**Comment by 3lvis** [comment]
@galinyonchev Hi, I got an example of this Core Data model in the `Tests` project => https://github.com/hyperoslo/Sync/tree/master/Tests

The issue is that your Core Data models don't have a primary key and your JSON doesn't have a primary key neither. You need this in order for Sync to differentiate objects. So you can either add `remoteID` to each of your models and `id` to each of your JSON objects or you can just select a **unique** Core Data attribute and make it a primary key. => https://github.com/hyperoslo/Sync#primary-key

Finally, Sync maps your API that should use `snake_case` into your Core Data models that should you `camelCase`. => https://github.com/hyperoslo/Sync#attribute-mapping

For example:  In the JSON `object_deleted` would be `objectDeleted` in Core Data.

Let me know if you need more information, but primary key and `snake_case` and `camelCase` are the only requisites for Sync to work.
