### ISSUE TITLE
Diff probelm for using remoteID

### ISSUE THREAD

**Issue by wuxiao356** [hyperoslo/Sync#161]
In my project, when a user added a new data entry, I saved it locally first by inserting it into the mainContext and saving it. Also I set this new data entry's remoteID to be the most recent data entry's remoteID + 1. Then I posted the new data to server. 

But later, when I tried to get all the data from sever and sync them with local core data. It ended with adding another new data entry not updating the one I saved locally before. That is, after syncing, the local core data had two new data entries with same remoteID. I thought the remoteID should be used to diff objects by default. How this would happen?

**Comment by 3lvis** [comment]
Hi @wuxiao356,

I remember this been reported earlier. Could you try saving your new data entry using a new backgroundContext instead of a mainContext?

I didn't set up the main context to be mutable, that's why you probably have this issues. If this fixes your problem I'll improve the documentation to be clear about this.

Have a great day :)

**Comment by 3lvis** [comment]
Closing since no feedback has been received from @wuxiao356
