### ISSUE TITLE
Sync applicability 

### ISSUE THREAD

**Issue by meoz** [hyperoslo/Sync#198]
Hi. I'm working on a syncing engine that syncs core data with an external server. Sync looks like a nice framework which could be of great use but it's applicability is not all clear to me. 
As far as I understood Sync can be used to convert and persist JSON objects coming from an external source like a web server / cloud to local core data objects. What's not clear to me is if Sync can 'sync' the other way around as well, taking the local changes from the core data model and upload them back into the cloud ?

**Comment by 3lvis** [comment]
Hi @meoz,

Sync has partially this feature, you still have to implement the networking part of it, since Sync doesn't do any networking at all.

But for example, if you update a `user` object and you want to update it in your server using a `PUT` you can generate the JSON for this NSManagedObject.

More information here:

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper#json-representation-from-a-nsmanagedobject

I hope this works for you! Let me know if you have any other questions.

Have a great day ☀️
