### ISSUE TITLE
How to map relationships that don't have remote IDs?

### ISSUE THREAD

**Issue by falkobuttler** [hyperoslo/Sync#204]
Hello @3lvis,

I consider using Sync as a replacement for RestKit in my project. While RestKit is super powerful, it is also very complicated, and outdated. 

Now to my question? How can I map nested objects that don't return an unique ID? But based on their parent object they are unique? 

Example:

```
{
  "id": "578613fc037aaaa70a829",
  "firstname": "John",
  "lastname": "Doe",
  "address": {
    "street": "Main Street",
    "city": "Naples",
    "state": "FL",
  },
}
```

I get an `user` with an unique ID. I can easily map that object. But the embedded `address` doesn't have any exposed ID. With RestKit it was possible to map the parent's ID to this child to make it unique. Basically take `user.id` as remote ID. 

Is there any way to do that with Sync?

**Comment by 3lvis** [comment]
@falkobuttler Hi Falko! It's great that you're giving Sync a try, I hope you like it.

There are two ways you can sync a JSON object that doesn't have a `remoteID`. You can either set one of it's [attributes as the primary key](https://github.com/hyperoslo/Sync#primary-key), or you can store the JSON object as NSData, I have done this myself in a couple of apps works pretty well. You can find more information on how to store dictionaries using Sync [here](https://github.com/hyperoslo/Sync#arraydictionary).

I hope this helps, let me know if we can do anything else to make the transition easier. 💐

**Comment by falkobuttler** [comment]
Hey @3lvis, neither of your recommended solutions works in this case though.

Storing it as NSDate would discard all of the benefits of an object model. And I can't use any of the properties a primary key because they are not unique. 

I was thinking more about of either a way of using the parent's primary key as the child's primary key or to generate a unique id based on the parent, i.e. `user_578613fc037aaaa70a829` as guid for the address. 
I was able to do something similar with RestKit using the metadata property or by using something like `parent.id` as allowed name as primary key.

**Comment by 3lvis** [comment]
@falkobuttler Hi Falko, sounds like we don't have a solution for your requirements out of the box. The quickest way for you to add this would be as you say to modify your JSON so it adds the parent id as the ID of the child object.

I'm sorry that there isn't a better way to do this.

**Comment by achirkof** [comment]
@3lvis Hi!
Today I met same problem when I decided to move all my synchronisation to Sync. Before I use Sync only for part of my app model and part of them I managed by "hand".
I would say it is very common situation when you have JSON with object or array of objects without `id`.
In my case JSON looks like this:
```json
"_id" : "Ryw7TgD69JYEgixL5", 
...
    "userWeight" : [
        {
            "weightValue" : 65.0, 
            "measuredAt" : ISODate("2017-01-11T14:39:11.125+0000")
        }, 
        {
            "weightValue" : 62.0, 
            "measuredAt" : ISODate("2017-03-04T17:55:49.290+0000")
        }, 
        {
            "weightValue" : 63.4, 
            "measuredAt" : ISODate("2017-03-07T22:15:00.290+0000")
        }
    ], 
    ... 
```
I don't need `id`'s for `userWeight` in my application and add it only to be able to sync is not very clean way.
I also tried to save `userWeight` as Binary Data, but I can't work whit it after unarchive because it returns `Any` instead of `Array`.
I also tried to set `measuredAt` as `sync.isPrimaryKey` but it didn't help.

Maybe we can think on another possible solution how to create related objects without `id`?

**Comment by xTheRamon** [comment]
Setting the date as the primary key is the solution here though. Your approach was right. We'll only have to find out what went wrong. Why didn't it work? Did you use ’YES’ as the value? Did you set a remote key too? I believe it is necessary to set both. 

PS. The Any (’id’) object returned from Binary data can simply be typecasted. But let's take the above approach! 👍🏼

**Comment by achirkof** [comment]
Hi @xTheRamon !
Yes, the idea to use Date field as id make sense. I set only property `sync.isPrimaryKey` equal to `true` for `measuredAt` and didn't set `sync.remoteKey` because remote field name in JSON equal to name of the field in core data entity. I thought it only needs when field name different. I will set also `sync.remoteKey` and check tonight.

About second approach. After unarchive the value and print it I see somthing like this:
```
__NSArrayI
(
        {
            "weightValue" : 65.0, 
            "measuredAt" : ISODate("2017-01-11T14:39:11.125+0000")
        }, 
        {
            "weightValue" : 62.0, 
            "measuredAt" : ISODate("2017-03-04T17:55:49.290+0000")
        }, 
        {
            "weightValue" : 63.4, 
            "measuredAt" : ISODate("2017-03-07T22:15:00.290+0000")
        }
    )
``` 
I don't know how to deal with it. Ideally I want to get array of dictionaries:
```
[
	["weightValue" : 65.0, "measuredAt" : ISODate("2017-01-11T14:39:11.125+0000")], 
	["weightValue" : 62.0,  "measuredAt" : ISODate("2017-03-04T17:55:49.290+0000")], 
	["weightValue" : 63.4,  "measuredAt" : ISODate("2017-03-07T22:15:00.290+0000")]
]
```
because I want to sort an array by date and get weight value.

**Comment by xTheRamon** [comment]
@achirkof Yeah! I believe for `isPrimaryKey` you explicitly need to set `remoteKey` too.
I would definitely try this approach since you want to sort values too.

Regarding the second approach, well, the value you printed is already an array. You probably have something like this:

```objc
id unarchivedObject = [NSKeyedUnarchiver unarchiveObjectWithData:managedObject.userWeight];
NSLog(@"%@", unarchivedObject);
```

The only thing you need to do is:
```objc
NSArray *arrayObject = (NSArray *)[NSKeyedUnarchiver unarchiveObjectWithData:managedObject.userWeight];
NSLog(@"Array: %@", arrayObject);
NSLog(@"Dictionary entry: %@", arrayObject[1]); // Should be weightValue: 62.0
```

**Comment by achirkof** [comment]
My difficulty is in type of `fitnesProfile` entity because it is array of single value:
```swift
let requestFitnesProfile = NSFetchRequest<NSFetchRequestResult>(entityName: "FitnesProfile")
let userFitnesProfile = try! dataStack.mainContext.fetch(requestFitnesProfile) as! [FitnesProfile]
```
Now `userFitnesProfile` is array of single `FitnesProfile`. After that i do:
```swift
let weight = NSKeyedUnarchiver.unarchiveObjectWithData(userFitnesProfile[0].userWeight as! Data)
```
Then `weight` is `__NSArrayI`. As I understand it is Obj-C `NSArray` type. And after I can't typecast it. I have no access to Xcode right now to check. I will try both approaches tonight.

**Comment by achirkof** [comment]
@xTheRamon you will be right. When I set both properties `isPrimaryKey` and `remoteKey` for `measuredAt` field synchronisation works as expected. 

About second approach. I can't get subscripts of `weight[0]` because type `Any` have no subscriptions. And I don't understand how to cast it to `Array`. I also have no any methods to do anything with `weight`.

![screen shot 2017-04-18 at 21 50 10](https://cloud.githubusercontent.com/assets/1292136/25147826/7c853c24-2481-11e7-8e6c-529abbd61644.png)

**Comment by 3lvis** [comment]
Hi!

You should be able to cast the result of unarchiveObject to Array.

Something like this:

```swift
if let array = NSKeyedUnarchiver.unarchiveObjectWithData(data) as? [String: Any] {
    //...
}
```

**Comment by achirkof** [comment]
@3lvis unfortunately can't

![screen shot 2017-04-18 at 23 35 48](https://cloud.githubusercontent.com/assets/1292136/25151882/e01ffff4-248f-11e7-8925-fee16c760032.png)

**Comment by dneykov** [comment]
I'm stuck with same problem cannot use unarchiveObject.
Any advice?

**Comment by xTheRamon** [comment]
@dneykov please see https://github.com/SyncDB/Sync/issues/204#issuecomment-294754585, this is the recommended way to solve this 'bug'.

**Comment by achirkof** [comment]
@dneykov no, I have decided to use separate entity.

**Comment by dneykov** [comment]
My situation is little bit different. Here is my json:

``` json
{
    "id": "2",
    "name": "Test name",
    "description": "test",
    "max_distance_walk": "250",
    "max_fee_hour": "3",
    "options": {
        "option1": "0",
        "option2": "0",
        "option": "0"
    },
    "updated_at": 1486644111
}
```

I have options as Binary Data and I want to access them as Dictionary as it says here https://github.com/SyncDB/Sync#retrieving-mapped-dictionaries
Is returning Any and I cannot convert it to anything.

**Comment by dneykov** [comment]
Finally it works. Here is my solution.

``` swift
func checkOption(key: String) -> Bool {
    guard let options = self.getOptions() as? [String: String] else {
        return false
    }
        
    guard let option = options[key] else {
        return false
    }
        
    return option.isEqual("1")
}
    
private func getOptions() -> Any? {
    return NSKeyedUnarchiver.unarchiveObject(with: self.options! as Data)
}

**Comment by 3lvis** [comment]
I see, looks like the solution was casting to `[String: String]`.

**Comment by 3lvis** [comment]
Updated the README https://github.com/SyncDB/Sync/blob/master/README.md#retrieving-mapped-arrays
