### ISSUE TITLE
Nonexistent keys in JSON should reset the object value to default on update

### ISSUE THREAD

**Issue by Jonge** [hyperoslo/Sync#255]
Our API doesn't send all data and we use default values if they aren't contained in the JSON. This is not a problem when creating the object, but there is an issue when updating.

Say we have a `NSManagedObject` subclass `Computer`. It has an attribute `turnedOn` of type `Bool` and default value `NO` (`false` in Swift).

When we create the object, it has the `turnedOn` attribute set to `false` when the JSON doesn't contain the key.

When we receive a JSON with the key `turnedOn` set to `true`, it updates the attribute correctly.

But, when we now receive a JSON that doesn't contain the key `turnedOn`, it should reset that attribute back to default (by using `primitiveValueForKey:`). Instead it gets ignored and previous value is kept.

**Comment by xTheRamon** [comment]
Hi Jonge,

I think this is the way we want the Sync to work.
Many API's are not sending all fields, just the changed ones. This has to do with unnecessary overhead. They assume the client keeps the last value in mind.
I think in your case you should create a method that overwrites the whole object with default values just before the sync. 👍🏼

**Comment by 3lvis** [comment]
@xTheRamon is completely right. This was a change made in [NSManagedObject-HYPPropertyMapper](https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/blob/master/Source/NSManagedObject%2BHYPPropertyMapper.m#L13-L37) because we found that it's better to be explicit about _nilling_ attributes. Avoids a lot of bugs.

If you want to nil an attribute or use a default parameter as @xTheRamon said, is better for you to do this in another method.

To be clear, the way to _nullify_ an item would be by sending `null` in JSON:

```json
turne_on: null
```

**Comment by Jonge** [comment]
Oh alright then. Guess our APIs have different approaches, but that makes sense.

I wanted to keep it simple, but I think processing the JSON before passing it to Sync should work fine.

Thanks to both of you!
