### ISSUE TITLE
Possibility to save the image completely

### ISSUE THREAD

**Issue by RamonGilabert** [hyperoslo/Sync#45]
Right now, we're saving the URL of the image, maybe someone wants to save all the image, for some user case, like doing a ProfileImage, and you don't want to network all the time.

I was thinking in a UserInfo key, `hyper.saveDataImage`, or something like that.

I guess the best explanation would be, process the image if the user wants to.

**Comment by 3lvis** [comment]
It's an interesting idea, and probably would make this process a bit easier.

But downloading images should be done only when the user needs it, otherwise you'll end up storing a huge amount of images, using a lot of phone power for nothing.

The best way to download images in a UITableView for example is to start the download as soon as the user sees the view, and start the download only for the visible cells, when the user stars scrolling the in-progress downloads should be canceled and new ones should be started for the new visible cells.

We could probably make a different library to handle this, I've made it in many apps and is something I always wanted to do, but I don't think it belongs to Sync.

**Comment by RamonGilabert** [comment]
Right, but what about if we want to save the data of an image, as I said, a profile image for example, it would be like

**Comment by 3lvis** [comment]
This could be a different project, might be better if we keep Sync with dates, strings and numbers.

:)
